# Generated by Django 6.0 on 2026-01-12 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_message_product'),
        ('products', '0006_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='product',
        ),
        migrations.AddField(
            model_name='thread',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='products.product'),
        ),
    ]
