# Generated by Django 6.0 on 2026-05-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_message_is_deleted'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='communicati_is_dele_3a2c35_idx',
            old_name='communicat_is_deleted_idx',
        ),
    ]
