# Generated by Django 6.0 on 2026-05-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_rename_communicat_is_deleted_idx_communicati_is_dele_3a2c35_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_admin_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
