# Generated by Django 6.0 on 2026-04-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
