# Generated by Django 6.0 on 2026-04-06 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('communications', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='conversation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communications.thread'),
        ),
        migrations.AddField(
            model_name='report',
            name='listing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='target_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='role_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='accounts.roleapplication'),
        ),
        migrations.AddField(
            model_name='roleapplicationdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.roleapplication'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['-timestamp'], name='accounts_ad_timesta_767a88_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['admin', '-timestamp'], name='accounts_ad_admin_i_4e485b_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['action', '-timestamp'], name='accounts_ad_action_5c746b_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['target_type', 'target_id'], name='accounts_ad_target__01f567_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'category'], name='accounts_re_status_fa58f2_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', 'status'], name='accounts_re_user_id_57b061_idx'),
        ),
        migrations.AddIndex(
            model_name='roleapplication',
            index=models.Index(fields=['status', 'role_type'], name='accounts_ro_status_a283ac_idx'),
        ),
        migrations.AddIndex(
            model_name='roleapplication',
            index=models.Index(fields=['user', 'status'], name='accounts_ro_user_id_e44c8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roleapplication',
            unique_together={('user', 'role_type', 'status')},
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['org_type', 'is_verified'], name='accounts_or_org_typ_167f3d_idx'),
        ),
    ]
