# Generated by Django 6.0 on 2026-05-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                    ("reopened", "Reopened"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
