# Generated by Django 6.0 on 2026-02-16 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_report_is_active'),
        ('communications', '0003_remove_message_product_thread_product'),
        ('products', '0007_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='conversation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communications.thread'),
        ),
        migrations.AddField(
            model_name='report',
            name='listing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='report',
            name='target_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Issue'), ('user_behavior', 'User Behavior'), ('product', 'Product Issue'), ('message', 'Message Issue'), ('other', 'Other')], max_length=20),
        ),
    ]
