# Generated by Django 6.0 on 2026-02-18 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_report_conversation_id_report_listing_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleapplication',
            name='document',
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RoleApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='role_applications/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.roleapplication')),
            ],
        ),
    ]
