# Generated by Django 6.0 on 2026-02-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_roleapplication_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleapplicationdocument',
            name='description',
        ),
    ]
