# Generated by Django 6.0 on 2026-02-19 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_roleapplicationdocument_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('user_blocked', 'Blocked User'), ('user_unblocked', 'Unblocked User'), ('user_deleted', 'Deleted User'), ('user_role_changed', 'Changed User Role'), ('application_approved', 'Approved Role Application'), ('application_rejected', 'Rejected Role Application'), ('listing_removed', 'Removed Listing'), ('listing_restored', 'Restored Listing'), ('report_resolved', 'Resolved Report'), ('report_closed', 'Closed Report'), ('dispute_resolved', 'Resolved Dispute'), ('verification_approved', 'Approved Verification'), ('verification_rejected', 'Rejected Verification'), ('other', 'Other Action')], max_length=50)),
                ('target_type', models.CharField(help_text='Type of entity (User, Listing, NGO, etc.)', max_length=50)),
                ('target_id', models.CharField(help_text='ID of the target entity', max_length=255)),
                ('target_name', models.CharField(help_text='Name/description of the target', max_length=255)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='success', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for the action', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='accounts_ad_timesta_767a88_idx'), models.Index(fields=['admin', '-timestamp'], name='accounts_ad_admin_i_4e485b_idx'), models.Index(fields=['action', '-timestamp'], name='accounts_ad_action_5c746b_idx'), models.Index(fields=['target_type', 'target_id'], name='accounts_ad_target__01f567_idx')],
            },
        ),
    ]
