# Generated by Django 6.0 on 2026-02-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_adminactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(choices=[('user_blocked', 'Blocked User'), ('user_unblocked', 'Unblocked User'), ('user_role_changed', 'Changed User Role'), ('application_approved', 'Approved Role Application'), ('application_rejected', 'Rejected Role Application'), ('listing_removed', 'Removed Listing'), ('listing_restored', 'Restored Listing'), ('report_resolved', 'Resolved Report'), ('dispute_resolved', 'Resolved Dispute'), ('other', 'Other Action')], max_length=50),
        ),
    ]
