# Generated by Django 6.0 on 2026-05-28 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='donations.donationrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_donation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='donations_s_user_id_b97bcf_idx'), models.Index(fields=['donation_request'], name='donations_s_donatio_a44116_idx')],
                'unique_together': {('user', 'donation_request')},
            },
        ),
    ]
