# Generated by Django 6.0 on 2026-05-28 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedScrapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scrap_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='recycle.scraprequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_scrap_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='recycle_sav_user_id_115db7_idx'), models.Index(fields=['scrap_request'], name='recycle_sav_scrap_r_c79cf4_idx')],
                'unique_together': {('user', 'scrap_request')},
            },
        ),
    ]
