# Generated by Django 6.0 on 2026-02-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0002_scrapcategory_scraprequest_delete_scraprates'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraprequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='scraprequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
