# Generated by Django 6.0 on 2026-02-23 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0003_scraprequest_latitude_scraprequest_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scraps/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('scrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recycle.scraprequest')),
            ],
        ),
    ]
