# Generated by Django 6.0 on 2026-02-27 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0005_alter_scraprequest_status_scrapoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapoffer',
            old_name='message',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='scrapoffer',
            old_name='created_at',
            new_name='offer_date',
        ),
        migrations.AddField(
            model_name='scrapoffer',
            name='offered_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapoffer',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapoffer',
            name='scrap_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycler_offers', to='recycle.scraprequest'),
        ),
    ]
