# Generated by Django 6.0 on 2026-01-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('like new', 'Like New'), ('fair', 'Fair'), ('damaged', 'Damaged')], max_length=50),
        ),
    ]
