# Generated by Django 6.0 on 2026-05-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_admin_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
