# Generated by Django 6.0 on 2026-05-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_is_admin_reviewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_admin_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_admin_reviewed",
        ),
    ]
