# Generated by Django 6.0 on 2026-01-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_condition_remove_product_is_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('Recycled', 'Recycled'), ('Donated', 'Donated')], default='available', max_length=20),
        ),
    ]
