# Generated by Django 6.0 on 2026-01-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Recycled', 'Recycled'), ('Donated', 'Donated')], default='available', max_length=20),
        ),
    ]
