# Generated by Django 6.0 on 2026-01-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('recycled', 'Recycled'), ('donated', 'Donated')], default='available', max_length=20),
        ),
    ]
